### ISSUE TITLE
autotest_control related test not work in avocado

### ISSUE THREAD

**Issue by xutian** [avocado-framework/avocado-vt#254]
autotest_control related test case need archive autotest source, then transfer it into guest and execute autotest case in guest.  It doesn't work now, failed at archive autotest source if user install avocado and autotest from RPM.

17:12:46 ERROR| Traceback (most recent call last):

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py", line 578, in _run_avocado
    testMethod()

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py", line 360, in runTest
    self._runTest()

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/plugins/vt.py", line 498, in _runTest
    run_func(self, params, env)

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/virttest/error_context.py", line 135, in new_fn
    return fn(*args, **kwargs)

17:12:46 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 107, in run
    hotplug_test.start_test()

17:12:46 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 68, in start_test
    self.run_sub_test()

17:12:46 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/hotplug_mem.py", line 28, in run_sub_test
    run_virt_sub_test(*args)

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/virttest/utils_test/__init__.py", line 1223, in run_virt_sub_test
    run_func(test, params, env)

17:12:46 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/autotest_control.py", line 33, in run
    ignore_session_terminated=ignore_sess_terminated)

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/virttest/utils_test/__init__.py", line 943, in run_autotest
    process.run(cmd)

17:12:46 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 949, in run
    raise CmdError(cmd, sp.result)

17:12:46 ERROR| CmdError: Command 'cd /usr/lib/python2.7/site-packages/autotest; tar cvjf /tmp/avocado_tihfPi/autotest.tar.bz2 client/* --exclude=client/results* --exclude=client/tmp --exclude=client/control* --exclude=*.pyc --exclude=*.svn --exclude=*.git --exclude=client/tests/virt/*' failed (rc=1)

**Comment by lmr** [comment]
My ideas to deal with it:

1) Disable support for running autotest control if using rpm
2) Fix the code that runs autotest control by:
a) detect if we're on an rpm install
 if yes, install an autotest package in the host and skip this tar step
 if no, use the current "tar and copy to the vm" approach.

I'm sorry I did not test this case while merging virt-test and avocado-vt.

That said, I'm afraid I won't be able to work on this during the next couple of months. Copying @ldoktor and @clebergnu to see what are their thoughts on the issue.

**Comment by clebergnu** [comment]
I'm not sure this is something introduced by avocado-vt. My initial feeling is that this goes back to the plain virt-test days, when using autotest from packages.

In fact, even when *not* using virt-test/avocado-vt, I believe we had the same problems with autotest *server* tests when running out of packages.

So, I agree this should be fixed, since it's part of valid and necessary test cases.

I agree with the suggestions given by @lmr , specially about using packages on the remote system, since it'd too error prone to construct a `/usr/local/autotest` out of the available packaged contents on the "source" system. The implementation may actually be easier, since it would involve (optionally) setting a repo and running a single command to install the packages.

If we go to those lengths, we may want to share the same implementation with Avocado itself, since the remote and vm plugins rely on having avocado packages already installed. It'd be nice to (optionally) be able to install avocado on fresh machines before the testing itself happens.

So, lot's of food for thought. Now let's try to get some real action going.

**Comment by xutian** [comment]
now it works for us, so close this issue.  
@clebergnu and @lmr  thanks your comments.
