### ISSUE TITLE
Object of type Params is not JSON serializable is most recent Avocado

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#3272]
Test runs with master branch Avocado VT and Avocado results in a fatal error aborting the entire run:

```
Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/avocado/core/job.py", line 627, in run_tests
    jobdata.record(self, sys.argv)

  File "/usr/lib/python3.9/site-packages/avocado/core/jobdata.py", line 89, in record
    json.dump(job.config, job_config_file,

  File "/usr/lib64/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:

  File "/usr/lib64/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)

  File "/usr/lib64/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks

  File "/usr/lib64/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)

  File "/usr/lib/python3.9/site-packages/avocado/core/nrunner.py", line 105, in default
    return json.JSONEncoder.default(self, config_option)

  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type Params is not JSON serializable
```

I am sharing this in case there is interest, possibly has to be fixed before the next Avocado VT release or the VT release won't make sense.

**Comment by willianrampazzo** [comment]
Hi @pevogam, do you have a reproducer? I could not reproduce it.

**Comment by pevogam** [comment]
> Hi @pevogam, do you have a reproducer? I could not reproduce it.

This happens in our in-house CI which always fetches the most recent `master` Avocado + Avocado VT, then runs a small selection of tests. It seems the job recording is storing the job.config in new ways that it didn't before (this fails after the LTS release). So I assume all job.config values must be strings?

**Comment by richtja** [comment]
Hi @pevogam, we did the changes to the JSON serialization in https://github.com/avocado-framework/avocado/pull/5065/commits/2aaef516ec621ed69814a7ae4e25916a0f619b39 and https://github.com/avocado-framework/avocado/commit/9f1585556e260fef583afa66682c97bc345c5c64 which might cause this problem, but I could not reproduce it either. So if you please give me more info about your test, I will look at it.

**Comment by pevogam** [comment]
@richtja Thanks for the directions regarding commits. The problem could also be local to me due to patches so I will investigate and let you know. If this turns to be the case I will simply close this issue.

**Comment by pevogam** [comment]
Hi @richtja, indeed the problem seems to be local to our plugin as we make use of Avocado VT's `Params` class to pass additional dictionary-enhance parameters to our plugin. In particular we produce some job config attributes like `config.run_params` to make use of some VT parameters that are generic for our complete job and not just particular VT tests. I guess I should extend the `ConfigEncoder` to work for us then? Can we disable this `config` JSON serialization at least for our own use somehow?

**Comment by richtja** [comment]
Hi @pevogam  yes the `ConfigEncoder` is the Encoder for JSON serialization of job data. And unfortunately, there is no configuration option for disabling the jobdata JSON serialization. As a hot fix, you can remove the [serialization](https://github.com/avocado-framework/avocado/blob/master/avocado/core/jobdata.py#L88) in your branch.

**Comment by pevogam** [comment]
Indeed, this is exactly what I did yesterday as a quick fix. What do you think should be the long term approach here though? Should we extend the encoders to extend the JSON serialization of all types or should we be able to also disable this procedure? The first brings with itself increased coupling and thus potential breakage (maintenance costs) while the second might not be the best way you imagine Avocado being used.

**Comment by richtja** [comment]
I don't have enough information about your use-case, so I don't know how difficult it will be to extend the JSON serialization, but I think we should stick to the python built-in types. Is there any reason to save`Params.data` to the `config.run_params` instead of `Params`. Because the `ConfigEncoder` supports the dict type.

**Comment by richtja** [comment]
> Yes, the reason is the additional functionality that `Params` provides in addition to the traditional python dictionary type like `Params.objects()`, automatic conversion of types, and others. This also stems from our original use of Autotest command line parameters in the past and is still valid because we might want to specify suffixed and other parameters there like:
> 
> ```
> avocado <own-plugin> -- images_vm1=A,B nics_vm2=C,D
> ```
> 
> and our command line processing makes use of all additional information in these suffixed scopes to parse details. We then pass these `Params` objects down the calling chain and forcing serialization like the commits above means that we have to constantly convert them back and forth in order to be able to use them.

It is strange to me that this problem occurs now after the [avocado-framework/avocado@9f15855](https://github.com/avocado-framework/avocado/commit/9f1585556e260fef583afa66682c97bc345c5c64) because the basic JSON serialization of job `config` is in avocado from [ avocado-framework/avocado@1335f32](https://github.com/avocado-framework/avocado/commit/1335f328754a0635bc54a632bfac616f25bb0615#diff-b3102b03385a9596adc5ba2915b9512b70398119c6aa279d8690c1665b806f2a). Also, I am not sure if the job `config` is the right place for your use-case. Have you considered using the avocado variants, which can help you to store avocado prams?

> 
> In short, there could be valid cases where one would like to use enhanced dictionary or some other data type as part of the job `config` and the current seems pretty restrictive to me. What is your opinion about these comments?

The problem with other data types in job `config` is, that the job `config` data are gathered from three sources. Config file, command line and Job API and each of these sources has its specific. And we need to have the job config serializable, because we are serializing them pro the avocado [runners](https://github.com/avocado-framework/avocado/blob/master/avocado/core/nrunner.py#L231). So I think that we should stay with the python built-in types in job `config` for easier manipulation. @clebergnu, @beraldoleal any opinion here.

**Comment by beraldoleal** [comment]
@richtja @pevogam, configs must be serialized because it was designed not only to save this for 'replay' but also send over external environments during the actual run step.

> Also, I am not sure if the job config is the right place for your use-case. Have you considered using the avocado variants, which can help you to store avocado prams?

Yes, this would be a valid option if those parameters are need for the tests. However if this is something needed to change the  plugin behavior I would say the config would be better.

> So I assume all job.config values must be strings?

Currently we support any valid data supported by `json.JSONDecoder.decode` plus "sets".

> I guess I should extend the ConfigEncoder to work for us then? Can we disable this config JSON serialization at least for our own use somehow?

I'm not sure here. If we keep adding custom encoders here for every plugin needs, this might be a problem. Unless I'm missing something, those are used only to record/restore in case of "replay". So I guess disabling this per user is a valid request.

However before implementing this "disable" feature, I think I found the issue. In fact we might have a bug on Avocado side. Give me a few minutes to confirm.

**Comment by beraldoleal** [comment]
@pevogam can you test with this, please?

https://github.com/avocado-framework/avocado/pull/5198

**Comment by pevogam** [comment]
> @pevogam can you test with this, please?
> 
> [avocado-framework/avocado#5198](https://github.com/avocado-framework/avocado/pull/5198)

Sure, thanks a lot @beraldoleal for going the extra mile.

**Comment by pevogam** [comment]
Fixed via https://github.com/avocado-framework/avocado/pull/5198.
