### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado-vt#3323]
Got the following warning with Python 3.10, which led me to open this issue for having the update to the corresponding parts in VT.
```
$ python
Python 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
<stdin>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
```

Reference:
https://github.com/avocado-framework/avocado-vt/blob/2a9241a92ae88ddbbd0c306879be0ae94b87aed5/avocado_vt/utils.py#L128-L129
https://docs.python.org/3.10/library/importlib.html?highlight=importlib#module-importlib

**Comment by ana** [comment]
@luckyh You might want to do something like this:
https://github.com/avocado-framework/avocado/commit/dfc340f1a0b0aeddbf6699e49e94b75ed080137c

**Comment by luckyh** [comment]
@ana thank you for the information!

**Comment by bgartzi** [comment]
I can't assign it to myself, but I'll take it.

**Comment by bgartzi** [comment]
Hi all,

I had a quick check of the scope of the issue. It seems that there are a total of 10 (6+4) imp+importlib  uses. Generally speaking, they're used for 2 objectives:

1. Importing test cases that are going to be executed in the test loop.
2. Importing some autotest functionalities, which shouldn't be supported in the future (#2963, #3205).

The way of importing modules is quite heterogeneous so it seems quite reasonable to implement an _standarized_ way of doing this inside avocado-vt from now on.  One way could be using a similar approach to the one from avocado. Brief pseudocode:

```python
def import_module(module_name, module_dir=None):
    """
        desc
    """
    if module_dir:
        sys.path.insert(0, module_dir)
    try:
        module = importlib.import_module(module_name)
    except:
        raise whatever_ModuleNotFoundException
    finally:
        if module_dir:
            sys.path.pop(0) 
```
This could work, as it could mitigate the deprecation issue and would also fit with the autotest/py2 cases while they are completely removed from the code. 

The real problem comes with the _placement_ of this piece of code. In my opinion there are three ways of approaching this:

1. Using a similar piece of code anywhere we want to do a dynamic import: Well... this would clearly involve maintenance issues. It wouldn't provide a standard way of doing things in the future.
2. Creating a new virttest module to implement the general way of importing tests: As discussed with @luckyh This would change the API of the framework, and could give the users the ability of importing whatever they want dynamically in the test execution environment. (It could be made private, but there could still be some vulnerability risks to be taken into account).
3. New function inside an existing virttest module: This also would change the API of the framework and would involve the same issues I mentioned before.  Plus a personal temptation of implementing it into utils_misc which would increase its entropy, and I don't really feel this method fits with the purpose of other methods in that module.

I'd like to know about your opinion and the one from other maintainers you consider.

Thank you!

**Comment by luckyh** [comment]
>  2. Creating a new virttest module to implement the general way of importing tests: As discussed with @luckyh This would change the API of the framework, and could give the users the ability of importing whatever they want dynamically in the test execution environment. (It could be made private, but there could still be some vulnerability risks to be taken into account).

I'd prefer this option because, from my perspective, the wrapper we're going to introduce is a low-level utility which could be only used by the VT project (or more accurately, the `virttest` package). And I believe if other projects for some reason would want to consume this utility, providing high-level APIs to them instead would be a better choice for us (e.g. `load_test` vs. `import_module`). 

Currently, there is no existing private modules inside virttest, therefore I think we have to introduce a new one for the placement of this utility, and it could be `virttest._wrappers` or something else.
