### ISSUE TITLE
TODO: JeOS guest Image for ppc64le

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado-vt#421]
Based on the below issue, it is good to have the arch specific JeoS maintained and can be pulled bydefault. 
https://github.com/avocado-framework/avocado-vt/issues/420

Expectation of this issue is to host the JeOS for ppc64le and point as default when run on powerpc.

Needs a JeOS image to be hosted- Needs a clarity on this if it is already in plan or any support needed for the same. Thanks in advance.

**Comment by sathnaga** [comment]
@lmr @ldoktor @will-Do @xutian your comments pls

**Comment by ldoktor** [comment]
Hello Satheesh, as far as I know we don't have resources to maintain the ppc JeOS image so we don't plan to add it any time soon. If you want to become the maintainer of the ppc64 JeOS I think that can be arranged.

**Comment by sathnaga** [comment]
@ldoktor Sure, I can maintain ppc64 JeOS, If you can share necessary steps, I would start doing it.

**Comment by clebergnu** [comment]
@sathnaga the x86_64 JeOS are created based on an unattended_install[1] test run, which uses a kickstart[2] file.

A command such as:

```
$ avocado run io-github-autotest-qemu.unattended_install.cdrom.http_ks.default_install.aio_threads --vt-guest-os Linux.JeOS.21.x86_64.i440fx
```

Should result in a fresh `~/avocado/data/avocado-vt/images/jeos-21-64.qcow2`. This image can be compressed (we're using 7z) and can be made available as an asset file.

Since Fedora 21 is pretty old, I'm adding both Fedora 21 and 22 x86_64 (and the corresponding JeOS configuration) to avocado-vt. Once that is merged, you can run the given commands, just changing the guest os.

Once all that works for you, than it'd be time to tweak those files and create the Jeos definitions based on Fedora ppc64le.

[1] - https://github.com/avocado-framework/avocado-vt/blob/master/virttest/tests/unattended_install.py
[2] - https://github.com/avocado-framework/avocado-vt/blob/master/shared/unattended/JeOS-21.ks

**Comment by clebergnu** [comment]
@sathnaga the mentioned addition of Fedora/JeOS 22/23:

https://github.com/avocado-framework/avocado-vt/pull/434

**Comment by clebergnu** [comment]
@sathnaga we now have more storage space on the official "assets" server.  If you feel like this is worth doing, we can post JeOS (25) ppc64le there as well.

**Comment by sathnaga** [comment]
we have the JeOS images for ppc64le, Thanks @ldoktor @clebergnu , closing this issue.
